# Generated by Django 4.0.2 on 2022-02-16 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import food.utils.model_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AztBaseModel',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('index', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('translations', models.CharField(blank=True, max_length=1000)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-date_of_update'],
            },
            bases=(food.utils.model_utils.AztLocaleModel, models.Model),
        ),
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('iso', models.CharField(max_length=15, unique=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Locale',
                'ordering': ['-date_of_update'],
            },
        ),
        migrations.CreateModel(
            name='UsedID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRanges',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('min_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('time_unit', models.CharField(default='min', max_length=30)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('locale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_range', to='food.locale')),
            ],
            options={
                'verbose_name_plural': 'TimeRanges',
                'ordering': ['-date_of_update'],
            },
            bases=(food.utils.model_utils.AztLocaleModel, models.Model),
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(null=True, upload_to='images/restaurants/main/')),
                ('card_image', models.ImageField(null=True, upload_to='images/restaurants/card/')),
                ('index', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('translations', models.CharField(blank=True, max_length=1000)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='food.locale')),
                ('time_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='food.timeranges')),
            ],
            options={
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-date_of_update'],
            },
            bases=(food.utils.model_utils.AztLocaleModel, models.Model),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/food/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('index', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('translations', models.CharField(blank=True, max_length=1000)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='food.categories')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='food.locale')),
            ],
            options={
                'verbose_name_plural': 'Food',
                'ordering': ['-date_of_update'],
            },
            bases=(food.utils.model_utils.AztLocaleModel, models.Model),
        ),
        migrations.AddField(
            model_name='categories',
            name='locale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='food.locale'),
        ),
        migrations.AddField(
            model_name='categories',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='food.restaurants'),
        ),
    ]
