# Generated by Django 4.0.2 on 2022-02-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeranges',
            name='translations',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
