# Generated by Django 4.0.2 on 2022-02-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_timeranges_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.CharField(default='2022-02-17 05:44:33.781168', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.CharField(default='slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='slug',
            field=models.CharField(default='sdasdas', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
