# Generated by Django 4.0.2 on 2022-02-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_categories_slug_food_slug_restaurants_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
