# Generated by Django 4.0.2 on 2022-02-17 07:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import food.utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_categories_slug_alter_food_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/food/')),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('index', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('translations', models.CharField(blank=True, max_length=1000)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='food.categories')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='food.locale')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-date_of_update'],
            },
            bases=(food.utils.model_utils.AztLocaleModel, models.Model),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
