# Generated by Django 4.0.2 on 2022-02-17 07:45

from django.db import migrations, models
import django.db.models.deletion
import food.utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_products_delete_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('translations', models.CharField(blank=True, max_length=1000)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('date_of_add', models.DateTimeField(auto_now_add=True)),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='food.locale')),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['-date_of_update'],
            },
            bases=(food.utils.model_utils.AztLocaleModel, models.Model),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='food.Tags'),
        ),
    ]
